
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or fallback to the default values
const SUPABASE_URL = "https://hcdqlbuuybjjcvqxcscp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZHFsYnV1eWJqamN2cXhjc2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTU0MjksImV4cCI6MjA1NjkzMTQyOX0.IlYygkr_b8HwxxCo4Q-krbQwFxJ5eausm0d0NZ-EnbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
